### PR TITLE
[macOS packaging] Increase size of sparse image

### LINKED ISSUE #816: [macOS packaging] Sparse image too small
- When packaging MUSICardio, the sparse image runs out of space before the packaging finishes.

- Resizing 'Medinria.sparseimage'  to 2Gb fixes the issue

### PR DESCRIPTION
**Pull request by mjuhoor**
- Fixes #816 
- Increase size of sparse image when packaging on macOS

### CODE REVIEW

**Review by mathildemerle — APPROVED** [review]

**Comment by mathildemerle** [comment]
Tested and it works

**Review by paulineMig — APPROVED** [review]

**Comment by Florent2305** [comment]
@mjuhoor Est-ce tu peux m'expliquer un peux comment tu es arrivé à te dire que c'était la solution

**Comment by mjuhoor** [comment]
At some point in the packaging process, the script copies all the frameworks and plugins in the attached sparse image.
Before this PR, the copying fails (you get an error message from command 'cp') for some plugins because the sparse image is full, so resizing it fixes the problem.

**Comment by Florent2305** [comment]
@mjuhoor Thank you for your explanation. Great job.

**Pull request merged**
