### PR TITLE
Add a colormap for images that are label maps

### PR DESCRIPTION
**Pull request by ocommowi**
A tentative binary map LUT to better see label images. Tell me what you think.

PS : by the way, this made us realize (me and RP) the LUT/transfer functions system in medinria is quite a bit crappy. @papadop : any chance your branch on that could be revived / finished soon ?

### CODE REVIEW

**Comment by msermesant** [comment]
@LoicCadour : how does it compare to the discrete LUT feature you developed in MUSIC?

**Comment by LoicCadour** [comment]
Actually I created a mode in the medClutEditor to switch between linear and discrete mode. I didn't create a color map, I just modify the current LUT according to the mode.

**Comment by ocommowi** [comment]
Well, here it's a LUT with a different color for each label.Since it is a LUT, it is adapted depending on the min max values as the other LUTs. It has advantages and disadvantages, let me know what you think of it.

**Comment by LoicCadour** [comment]
In MUSIC, we needed this discrete mode to clearly visualize few (in most cases 2 or 3)  groups of pixels according to their intensity values. For instance, pixels whose intensities belong to [0;100] are displayed in red, [101;200] in green etc. And this is very easily done by placing vertices on the histogram.
I think your colormap is more useful for label images, in our case we are playing with CT/MR images.

**Comment by mikejbuckingham** [comment]
@LoicCadour @ocommowi 

What's the consensus here? Can we merge this, close it, or is more discussion needed?

**Comment by LoicCadour** [comment]
I quickly tested this branch (with MUSIC) it was working fine. The things I've done with the ClutEditor are not really related, so I've nothing else to add.

**Comment by mikejbuckingham** [comment]
OK - will merge after the meeting, unless there are objections.

**Pull request merged**
