### PR TITLE
[Homepage] add a menubar, enhance the design

### PR DESCRIPTION
**Pull request by mathildemerle**
I'm happy to show you the work i've done for medInria 4 on the homepage of the application. My goal has been to get a more user-friendly, modern application, but it also simplifies the code in `medHomepageArea` and `medMainWindow` for instance. I tried to make it also more modular for customization.

First, the fixed issues:
 * Answer to the [Improve Home page ergonomics and style](https://github.com/medInria/medInria-public/issues/446) issue
 * Answer to the [Facilitate image import](https://github.com/medInria/medInria-public/issues/282) issue

This PR:
 * Create an application menubar which is accessible in every area of the application (and can be easily adapted in workspaces or toolboxes as far as i know)
 * Move the Settings, About, Logs, Help on the menubar, and display them in windows
 * Remove quickAccess workspace button in the status bar, add adaptative list of the workspaces in the menubar
 * The "View" menu is only enabled in regular workspaces (with views) 
 * Remove Close icon in the status bar. Move Fullscreen icon on the menubar (at right corner of the menubar)
 * "Browser" renamed "Import/export files" to be easier to understand for users. Default tab in medBrowser is the Filesystem one (also renamed "Import files" for better understanding)
 * The "Search a toolbox" button is moved in the menu
 * The logo and application description are moved on top of the homepage
 * The description and about text are saved in text files for a better modularity of the application
 * The columns of workspaces on homepage are `gridLayout`, and are adaptative (there is a max of elements vertically, and if needed a new column is created. It's important on fork projects where we add a lot of workspaces and the column is too tall. Here the number is 6, but it can be changed easily
 * The status bar is completely empty of buttons, and only show messages. It is ready to be removed in a work on the logs, as asked in [Job status widget](https://github.com/medInria/medInria-public/issues/448). The aim of the PR was not to change the log system.

### The homepage
homepage

### An example of window created through an action in the menu, here "Plugin Logs"
pluginsLogs

### The "Go to" menu where the list of workspaces is automatically done
workspaceMenu

I hope you'll enjoy.
:m:

### CODE REVIEW

**Comment by msermesant** [comment]
Can the menu appear as the usual menu bar in macOS ?
maybe we could leave the full screen buttons to the window managers.

**Review by nebatmusic — APPROVED** [review]

**Comment by mathildemerle** [comment]
> Can the menu appear as the usual menu bar in macOS ?
> maybe we could leave the full screen buttons to the window managers.

@msermesant i just tested and this menu bar on macOs is displayed in the OS menubar already :).

Concerning the full screen button, on macOS it's indeed the same as the one in the window bar. However, on Linux and Windows the "Maximize" window buttons are not real fullscreen actions. We still see the dock and OS status bars (the OS bars with the current running applications, notification widgets and favorites app). The fullscreen button in medInria switch the application to real fullscreen, hiding the OS bars

**Comment by msermesant** [comment]
great for the menu :-)

Agreed for the fullscreen.

**Review by Florent2305 — APPROVED** [review]
ok

**Pull request merged**
