### PR TITLE
[Dicom import] Fix DICOM import when path contains special characters

### LINKED ISSUE #534: [DICOM Import] Failure to import if path contains special characters
medInria will fail to import DICOMs if the absolute path contains special characters.

1 - create directory named ` isdé_&"&'é""  `
2 - place a dicom inside
3 - import in medInria -> failure

This was previously solved with a brutal `QTextCodec::setCodecForCStrings(QTextCodec::codecForName("UTF-8"));`
but this static function is gone in Qt5

### PR DESCRIPTION
**Pull request by mjuhoor**
Fixes #534 

Problem was due to string conversion from UTF-8 to Latin1.

This could be applied to other readers and/or writers.

### CODE REVIEW

**Comment by mathildemerle** [comment]
Beware of the windows system, it could create problem on it ^^

**Comment by mathildemerle** [comment]
@Florent2305 @mjuhoor did you find a way to solve this problem on Linux/Windows/Mac?

**Comment by Florent2305** [comment]
toLocal8Bit instead of toUtf8 is better under Windows systems but is not THE solution because ideogram and other spécial glyph doesn't feet correctly.
I work on a solution with compilation flag for dcmtk, I expect a result for tomorrow.

**Comment by Florent2305** [comment]
This is what was promised and this is what must be delivered.
I done a PR directly on the mjuhoor:fixDicomImport branche of @mjuhoor .
https://github.com/mjuhoor/medInria-public/pull/1

Please test and consider this PR.
If you want test my branche, it's Florent2305:fixDicomImport
Best Flo

**Pull request merged**
