### PR TITLE
Remove pch

### PR DESCRIPTION
**Pull request by papadop**
This removes completely (hopefully) the precompiled header stuff in all CMakeLists.txt. 

This is mostly removal of code, except the two lines:

+set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/plugins/)
+set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/plugins/)

which I think I needed for something else (plugins/libs were not generated at the proper place?), but it is easier to keep them here.

### CODE REVIEW

**Comment by ocommowi** [comment]
Looks good to me. Can anyone on windows try to compile this and see if it's still works ?

**Comment by LoicCadour** [comment]
Can we remove (or at least rename) the RemovePch branch ? 
Because when typing *git checkout origin/RemovePCH* I go on *removePch*

**Comment by LoicCadour** [comment]
First glance: many linking errors, most of them with dtkCore.lib
Was medPch useful after all? I'll try to have a closer look.

**Comment by LoicCadour** [comment]
Forget what I wrote, it works fine!
We can merge it.

**Pull request merged**
