### PR TITLE
Switch to VTK8 and its OpenGL2 backend

### PR DESCRIPTION
**Pull request by ocommowi**
Replaces somewhat buggy qvtkgraphicsitem by QVTKOpenGLWidget (the newly officially supported QVTK widget for Qt5)

### CODE REVIEW

**Comment by rdebroiz** [comment]
That's god news!

**Comment by ocommowi** [comment]
Yep, that's great, good to see you still follow :) it actually solves quite a few bugs that were related to the use of the qvtkgraphicsitem. Still a lot to do on the viewers, but it does progress

**Comment by rdebroiz** [comment]
I'm using misterI more intensely now, both soft have good things that are not available in the other that's too bad...

**Comment by Florent2305** [comment]
Work on MS-Windows and Mac-OSX (10.12).

**Pull request merged**
