### PR TITLE
MODULE CMake Keyword

### PR DESCRIPTION
**Pull request by rdebroiz**
Use the MODULE CMake Keyword in add_library([...]) to produce lib having to be dynamically loaded (plugins).

see: http://www.cmake.org/cmake/help/v3.0/command/add_library.html

### CODE REVIEW

**Comment by papadop** [comment]
Just for curiosity, what is the difference with SHARED ??? The documentation is not very clear on the difference between SHARED and MODULE.... Otherwise, that seems a reasonable move given the documentation you pointed to. On the other hand, there is the fanous "If it works don't change it...", but I'm not totally endorsing this view.

**Comment by papadop** [comment]
And they are probably many other places where we want to make a similar change.

**Comment by rdebroiz** [comment]
> The documentation is not very clear on the difference between SHARED and MODULE....

As far as I know there is no difference on linux or windows plateforms: http://stackoverflow.com/questions/4845984/difference-between-modules-and-shared-libraries. But It gives one more hint about how the library is supposed to be used

> And they are probably many other places where we want to make a similar change.

Yep I know I did this only for the plugin using the new systeme provided by dtk. I told myself : if we have to do those things again let's do it the right way. There's a mechanism in CMake to tell that you want to build a plugin, so let's use it ;)

**Comment by rdebroiz** [comment]
About your last comment, maybe you didn't noticed that this PR will be merged on the `dev` branch.

**Pull request merged**
