### PR TITLE
Optimized PNG and removed wrong iCCP tag.

### PR DESCRIPTION
**Pull request by papadop**
This remove some "wrong" PNG tags that were generating warnings with newer libpng (fedora 21 and up). I use exiftool to rewrite the images as described in :
https://groups.google.com/forum/#!msg/adt-dev/rjTQ_STR3OE/-UcNQRISTKsJ

For reference, the error is documented here:
https://wiki.archlinux.org/index.php/Libpng_errors

Then I also took the opportunity to optimize (losslessly) the png files. I tried two tool optimpng and pngcrush. 

http://optipng.sourceforge.net/
https://en.wikipedia.org/wiki/Pngcrush

The first one being more effective (on one example), it is the one I used. Some files reduced dramatically. It won't change the speed of medInria but will reduce (slightly) the disk space it uses !!! 
Full stats (file old_size_after_exiftool new_size_after_optimpng):

./app/medInria/resources/icons/3DIcon.png 3647 3141
./app/medInria/resources/icons/about.png 4232 2911
./app/medInria/resources/icons/adjust_size.png 510 385
./app/medInria/resources/icons/AxialIcon.png 6778 3257
./app/medInria/resources/icons/backward.png 432 356
./app/medInria/resources/icons/camera_grey.png 9590 4114
./app/medInria/resources/icons/camera.png 10371 4552
./app/medInria/resources/icons/CoronalIcon.png 7727 3406
./app/medInria/resources/icons/cropping.png 2240 2233
./app/medInria/resources/icons/database.png 11926 10143
./app/medInria/resources/icons/folder.png 1377 1331
./app/medInria/resources/icons/forward.png 438 357
./app/medInria/resources/icons/home.png 1774 1758
./app/medInria/resources/icons/home_sc.png 5149 4073
./app/medInria/resources/icons/layer.png 574 573
./app/medInria/resources/icons/length.png 540 493
./app/medInria/resources/icons/magnify.png 1423 1280
./app/medInria/resources/icons/medCustomViewContainerA.png 786 165
./app/medInria/resources/icons/medCustomViewContainerB.png 811 156
./app/medInria/resources/icons/medCustomViewContainerC.png 957 180
./app/medInria/resources/icons/medCustomViewContainerD.png 980 186
./app/medInria/resources/icons/medCustomViewContainerE.png 898 207
./app/medInria/resources/icons/medCustomViewContainerF.png 1374 634
./app/medInria/resources/icons/play.png 430 353
./app/medInria/resources/icons/quit.png 290 269
./app/medInria/resources/icons/SagittalIcon.png 5637 2590
./app/medInria/resources/icons/save.png 704 684
./app/medInria/resources/icons/settings.png 458 354
./app/medInria/resources/icons/stop.png 351 294
./app/medInria/resources/icons/widget.png 329 252
./app/medInria/resources/icons/wlww.png 1023 978
./app/medInria/resources/icons/workspace_Diffusion.png 34075 29795
./app/medInria/resources/icons/workspace_Filtering.png 22676 19517
./app/medInria/resources/icons/workspace_Registration.png 18576 15532
./app/medInria/resources/icons/workspace_Segmentation.png 16580 13526
./app/medInria/resources/icons/workspace_Visualization.png 22840 20498
./app/medInria/resources/medInria.png 14565 11603
./app/medInria/resources/pixmaps/arrow-bot-disabled.png 214 153
./app/medInria/resources/pixmaps/arrow-bot.png 197 155
./app/medInria/resources/pixmaps/arrow-left-disabled.png 205 144
./app/medInria/resources/pixmaps/arrow-left.png 198 146
./app/medInria/resources/pixmaps/arrow-right-disabled.png 212 142
./app/medInria/resources/pixmaps/arrow-right.png 202 143
./app/medInria/resources/pixmaps/arrow-top-disabled.png 215 145
./app/medInria/resources/pixmaps/arrow-top.png 201 147
./app/medInria/resources/pixmaps/checkbox-disabled.png 131 122
./app/medInria/resources/pixmaps/checkbox-partial.png 243 171
./app/medInria/resources/pixmaps/checkbox.png 132 124
./app/medInria/resources/pixmaps/database_navigator_item_checker_checked.png 1295 1245
./app/medInria/resources/pixmaps/database_navigator_item_checker_unchecked.png 1156 1087
./app/medInria/resources/pixmaps/delete.png 2562 2273
./app/medInria/resources/pixmaps/drop-down.png 189 141
./app/medInria/resources/pixmaps/medInria-logo-dmg.png 125431 100793
./app/medInria/resources/pixmaps/medInria-logo-homepage.png 24927 24019
./app/medInria/resources/pixmaps/medInria-splash.png 40659 39695
./app/medInria/resources/pixmaps/plus-button.png 139 126
./app/medInria/resources/pixmaps/radio-checked-disabled.png 441 258
./app/medInria/resources/pixmaps/radio-checked.png 443 245
./app/medInria/resources/pixmaps/radio-disabled.png 419 419
./app/medInria/resources/pixmaps/radio-partial.png 485 297
./app/medInria/resources/pixmaps/tabwidget-pane.png 12245 3066
./app/medInria/resources/pixmaps/treeview-branch-closed.png 197 130
./app/medInria/resources/pixmaps/treeview-branch-open.png 196 142
./doc/img/medInria.png 14565 11603
./src/medCore.new/resources/icons/fourViews.png 864 543
./src/medCore.new/resources/icons/splitPresets.png 1561 669
./src/medCore.new/resources/pixmaps/closebutton.png 251 248
./src/medCore.new/resources/pixmaps/default_thumbnail.png 2421 1321
./src/medCore.new/resources/pixmaps/open.png 5576 3015
./src/medCore.new/resources/pixmaps/splitbutton_horizontal.png 198 182
./src/medCore.new/resources/pixmaps/splitbutton_vertical.png 146 113
./src/medCore.new/resources/pixmaps/tools.png 21005 6908
./src/medCore/resources/icons/fourViews.png 864 543
./src/medCore/resources/icons/splitPresets.png 1561 669
./src/medCore/resources/pixmaps/closebutton.png 251 248
./src/medCore/resources/pixmaps/default_thumbnail.png 2421 1321
./src/medCore/resources/pixmaps/open.png 5576 3015
./src/medCore/resources/pixmaps/splitbutton_horizontal.png 198 182
./src/medCore/resources/pixmaps/splitbutton_vertical.png 146 113
./src/medCore/resources/pixmaps/tools.png 21005 6908
./src-plugins/itkDataSHImage/icons/shs.png 18484 17890
./src-plugins/itkDataTensorImage/icons/tensors.png 11754 11194
./src-plugins/medSegmentation/pixmaps/magic_wand.png 2582 2397
./src-plugins/medVtkFibersData/icons/fibers.png 44407 39093
./src-plugins/medVtkView/resources/icons/3DIcon.png 3647 3141
./src-plugins/medVtkView/resources/icons/AxialIcon.png 6778 3257
./src-plugins/medVtkView/resources/icons/CoronalIcon.png 7727 3406
./src-plugins/medVtkView/resources/icons/cropping.png 2240 2233
./src-plugins/medVtkView/resources/icons/magnify.png 1423 1280
./src-plugins/medVtkView/resources/icons/SagittalIcon.png 5637 2590
./src-plugins/medVtkView/resources/icons/wlww.png 1023 978
./src-plugins/undoRedoRegistration/icons/BlueArrowRight.png 5007 4664

### CODE REVIEW

**Comment by mikejbuckingham** [comment]
Does what it says on the tin.

Will merge by noon tomorrow, unless objections.

**Comment by rdebroiz** [comment]
Good for me.

**Comment by NicolasSchnitzler** [comment]
updated to match current master

**Comment by mathildemerle** [comment]
@Florent2305 i tested the commit, and this PR is still relevant, i don't have anymore the "iCCP" message error

**Comment by Florent2305** [comment]
I approved

**Pull request merged**
