### PR TITLE
Glyph3d mapper same as #647 after rebase

### PR DESCRIPTION
**Pull request by nbaraka**
Glyph3d mapper same as #647 after rebase

### CODE REVIEW

**Comment by mathildemerle** [comment]
NB: from old PR closed https://github.com/medInria/medInria-public/pull/647

> @mathildemerle yes it solve #640 tbut he rendering is less smart in 3D. But It do not think that it is relevant to watch it in 3D. (but at least there is no crash)

**Comment by msermesant** [comment]
I use regularly 3D directions in 3D (through the tensor orientations in the diffusion workspace) to check the transmural changes of cardiac fibres, so the rendering of vectors is also relevant in 3D.

**Comment by Florent2305** [comment]
Indeed, at Rennes for exemple 3D is also regularly used for brain tensors applications.

**Comment by nbaraka** [comment]
The issue might not be from the this solution but from the 3D view. I have just opened a mesh (created from a mask) but that is thin (like this vector field) and it is difficult to watch it on 3D without another loaded 3D data. Maybe if you load this 2 vector field after the load of a full 3D data, you don't have this pb.

**Comment by mathildemerle** [comment]
I tried this Pull Request with the "Gradient.mha" data you sent us @nbaraka on 28/04/2020, there is no crash switching in 3D, but there is no displayed data in the view. If you rotate the view, you can see a thin layer, but i don't think your data should looked like that. And if you continue the rotation, medInria crash.
I put this PR on invalid for now, just to be sure not to merge it yet :)

**Comment by Florent2305** [comment]
The original issue is solved in #706

**Pull request closed without merging**
