### PR TITLE
Switch to cmake 3

### PR DESCRIPTION
**Pull request by ocommowi**

### CODE REVIEW

**Comment by mikejbuckingham** [comment]
As I recall, this has an issue with MacOS 10.6 or earlier?

If so, I will delay the merge until after 2.2.3 - let me know please.

**Comment by ocommowi** [comment]
Not to be in 2.2.3, rather for 2.3.0 and for when we reset the jenkins slaves (we'll put cmake 3 on those slaves I guess).

**Comment by rdebroiz** [comment]
It's now redundant with https://github.com/medInria/medInria-public/pull/265.
@ocommowi  do you care if I close this one ?

**Comment by ocommowi** [comment]
Does that answer your question ? ;)

**Pull request closed without merging**
